#!/bin/bash

# Downloads, deobfuscates, and decompiles versions
# with Ornithe mappings (anything fabric doesn't cover)

PYTHON=/usr/bin/python3
SCRIPT_PATH=$(dirname -- "$(readlink -f -- "$0")")

if [[ $# -eq 0 ]] ; then
  echo "No version specified"
  exit 1
fi

pushd $SCRIPT_PATH/..
$PYTHON downloader.py --libraries --server --force-version "$1" &&
$PYTHON download_fabric_mappings.py --ornithe "$1" &&
$PYTHON merge_jars.py "$1" &&
$PYTHON remap.py --from-ns official --to-ns named --tiny feather-{}.tiny --output {}-deobf.jar "$1" &&
$PYTHON generate_sources.py "$1"
popd

